<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccessorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('accessories')->insert([
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Mèo B',
                'image'             => 'images/accessories/meo_b.jpg',
                'quantity'          => 5,
                'breed'             => 'Mèo',
                'price'             => 80.50,
                'description'       => 'Mô tả chi tiết về phụ kiện cho mèo B',
                'evaluate'          => 4.0,
                'number_of_evaluate'=> 15,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'name'              => 'Phụ kiện Chó A',
                'image'             => 'images/accessories/chien_a.jpg',
                'quantity'          => 10,
                'breed'             => 'Chó',
                'price'             => 100.00,
                'description'       => 'Mô tả chi tiết về phụ kiện cho chó A',
                'evaluate'          => 4.5,
                'number_of_evaluate'=> 20,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
        ]);
    }
}
