<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cat;

class CatSeeder extends Seeder
{
    public function run()
    {
        Cat::insert([
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Golden Retriever',
                'breed' => 'Golden Retriever',
                'gender' => 'male',
                'age' => 3,
                'weight' => 25.0,
                'price' => 1400,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Bulldog',
                'breed' => 'English Bulldog',
                'gender' => 'female',
                'age' => 4,
                'weight' => 23.5,
                'price' => 1600,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ],
            [
                'name' => 'Doberman',
                'breed' => 'Doberman Pinscher',
                'gender' => 'male',
                'age' => 5,
                'weight' => 30.0,
                'price' => 2000,
                'color'=>"vang", 
                'description'=> 'sieu ngu ', 
                'image'=>"https://khopetshop.net/assets/images/category/thumbs/23042020042747_58236.jpg_thumb_300x180.jpg",
                'vaccinated'=>true, 
                'sterilized'=>false,
            ]
        ]);
    }
}
